### ISSUE TITLE
change PN for power connector to one that includes screws.

### ISSUE THREAD

**Issue by skot** [skot/bitaxeHex#13]
they even make cool colored screws;

[datasheet](https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/581/Metric_PCB_Screw_Terminals.pdf)

<img width="282" alt="image" src="https://github.com/skot/bitaxeHex/assets/140785/abf3bf79-e6eb-4770-87cd-e8c571b1d8c0">

**Comment by macphyter** [comment]
I changed the part number to the 7771 part with the non-colored screw.  The colored screws are harder to find.
