### ISSUE TITLE
Need diode on 5V regulator output

### ISSUE THREAD

**Issue by macphyter** [skot/bitaxeHex#18]
When USB is plugged in without the main power supply attached, 5V gets fed back through the 5V regulator to VIN.  This results in the 12V fans being powered by the USB 5V.  The 5V regulator should have a diode after the output caps to prevent this.

**Comment by benjamin-wilson** [comment]
On the 205 we just removed the USB power, it also removes a part.

**Comment by macphyter** [comment]
Removed USB power.
