### ISSUE TITLE
USB-C port needs clearance for plug enclosure

### ISSUE THREAD

**Issue by skot** [skot/bitaxeHex#2]
<img width="621" alt="image" src="https://github.com/skot/bitaxeHex/assets/140785/b93f9809-472f-4b4d-8526-e215d149b568">

USB-C plug enclosures can be pretty chunky sometimes. I think we need some more clearance between the USB-C receptacle and the ESP32. Especially if anyones uses the built-in antenna variant.

<img width="494" alt="image" src="https://github.com/skot/bitaxeHex/assets/140785/cdcddfd7-e025-42e5-80fa-25d0734753cd">

**Comment by benalleng** [comment]
What about using an upright receptacle?
https://www.molex.com/en-us/products/part-detail/2169890001 certainly not as many options as a standard unit but not any more expensive.

**Comment by macphyter** [comment]
@benalleng This could be an option if we are desperate, but I worry a little about durability.  That looks like it could get broken with enough sideways force.  In any case, I think we have room to move the existing connector over a little.  Thanks for your comment!

**Comment by macphyter** [comment]
I moved the USB-C connector away from the ESP32 as much as I could.  I think we should be good now.

**Comment by macphyter** [comment]
![image](https://github.com/skot/bitaxeHex/assets/20117182/b379f412-97f6-4c6c-88b2-263849058133)
