### ISSUE TITLE
SMD Buttons are too small

### ISSUE THREAD

**Issue by skot** [skot/bitaxeHex#22]
not very practical to press. Maybe something bigger like [TL3330AF260QG](https://www.digikey.com/en/products/detail/e-switch/TL3330AF260QG/1426836?s=N4IgTCBcDaICoBkDMKAMBBAYmAbKgigOIgC6AvkA)

**Comment by macphyter** [comment]
The buttons mentioned by skot were too wide to fit in the available space.  However I found some SMD buttons that have a nice round actuator and are narrow enough for the location.
https://www.digikey.com/en/products/detail/e-switch/TL3340AF160QG/1885973?s=N4IgTCBcDaIKIHEAsA2MB2AwgFQLQDkAREAXQF8g
I've removed the old buttons and added theses to the PCB layout.
