### ISSUE TITLE
Add Efuse

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxeHex#23]
For power monitoring and safety

**Comment by macphyter** [comment]
This is not so easy to do, given the limited amount of space around the main power input.  We'll have to think about this one.

**Comment by nguyentruong190** [comment]
It is not really necessary, if needed, a fuse can be used in series with the wire
![2dd2d9e22e3f9a380e8b21e9e97e772acb681a87_original](https://github.com/skot/bitaxeHex/assets/61081470/53d33885-29ac-479c-9011-7f54ba812a37)

**Comment by macphyter** [comment]
It was decided that the eFuse is too much of a burden at this point, since the TPS core voltage regulator already has shutdown capability for overcurrent and overvoltage.
