### ISSUE TITLE
Replace DigiKey Tape & Reel part numbers with Cut Tape ones in BOM

### ISSUE THREAD

**Issue by sarog** [skot/bitaxeHex#26]
The current BOM references DigiKey part numbers for Tape & Reel (TR) packages with minimum order quantities of 10,000+. They can be easily substituted with the Cut Tape (CT) ones.

| Ref | Current | Substitute |
|---|---|---|
| R2, R4 | RMCF0402FT17K8TR-ND | RMCF0402FT17K8CT-ND |
| R5 | RMCF0402FT10K0TR-ND | RMCF0402FT10K0CT-ND |
| R6 | YAG3115TR-ND | YAG3115CT-ND |
| R10 | 311-26.1KLRTR-ND | 311-26.1KLRCT-ND |

**Comment by macphyter** [comment]
Done!
