### ISSUE TITLE
Extender Voltage Range

### ISSUE THREAD

**Issue by Mairex2000** [skot/bitaxeHex#3]
As this would be a perfect Rig for PV powered mining wouldn't it be a good idea to have a greater Voltage In Range so that it could be powered from a 24 Volt Solar System? In this system you would have lower amps and it would have a better overall performance.

**Comment by skot** [comment]
That seems like a good idea to me; do you have a buck regulator in mind that can do this? We need an adjustable 4.5V output.

**Comment by Mairex2000** [comment]
To be honest: No, but I think it could be worth thinking about an PV moppt tracker instead.

**Comment by macphyter** [comment]
This is a cool idea... but the vast majority of users will be plugging this into a wall socket.  It also complicates the fan supply voltage, which use 12V now.  Lets put this on the back burner for now, and once things are working maybe consider doing a special "solar version"?

**Comment by macphyter** [comment]
No plans for extended voltage range at this time.
