### ISSUE TITLE
unrouted tracks on board

### ISSUE THREAD

**Issue by chenyang2151** [skot/bitaxeHex#43]
![屏幕截图 2024-06-27 080553](https://github.com/skot/bitaxeHex/assets/6297019/17efdfcf-4d96-4f7a-8af3-da2d775078e0)

**Comment by chenyang2151** [comment]
U15 /vdd1 have hole 
![Uploading 屏幕截图 2024-06-27 081106.png…]()

**Comment by chenyang2151** [comment]
![屏幕截图 2024-06-27 081106](https://github.com/skot/bitaxeHex/assets/6297019/1ab1640d-6172-49f3-9249-aec7ece496de)

**Comment by chenyang2151** [comment]
U15 /vdd1 have hole

**Comment by skot** [comment]
Another airwire ![image](https://github.com/skot/bitaxeHex/assets/140785/92ae1ffb-a0ac-4bb3-95b4-106e45484df3)

**Comment by chenyang2151** [comment]
hex use espminer 2.1.9 direct？ what is named broad version ？

**Comment by macphyter** [comment]
This is very strange.  Those missing connections don't show up on my KiCad DRC.  I don't know why.

**Comment by macphyter** [comment]
Fixed.

**Comment by chenyang2151** [comment]
the next table is not connects'

**Comment by aaron3481** [comment]
same, my drc does not notice me too. we found this airwrie by eye T_X

**Comment by chenyang2151** [comment]
is here 
![image](https://github.com/skot/bitaxeHex/assets/6297019/44802c32-c2de-47d4-98f6-bdb2c6679d16)
