### ISSUE TITLE
Heatsink hole spacing

### ISSUE THREAD

**Issue by jeca32** [skot/bitaxeHex#5]
can we spread the mounting holes of the PCB Heatsink  from 60.5 mm to 59,5 mm. there is a high risk of breaking the drill bit when drilling.
![Rad_PB](https://github.com/skot/bitaxeHex/assets/89108682/32a2f92b-3cee-4a43-bf08-60134cf93897)
![Rad_PB2](https://github.com/skot/bitaxeHex/assets/89108682/bb94e0d1-6caf-45a6-b47a-817c80bc6fbc)
![Heatsink_Mod_V2](https://github.com/skot/bitaxeHex/assets/89108682/fec6ade8-972b-499f-8533-f69dc106a92a)

**Comment by macphyter** [comment]
The CAD model of the heatsink is not a perfect representation of the fin spacing, so those holes may or may not end up between fins.  In any case, the holes should not be drilled that deep.  Just enough to tap some threads in the base.
